application: civic-shell-94403 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
  application_readable: true
# application_readable required so images can be read to be sized 
# by the python code

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: servepage.app


libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest